#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2008-2016 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

'''
Compose a multi-page indirect DjVu document in an efficient way.
'''

from __future__ import with_statement

import argparse
import os
import struct
import subprocess

DJVU_TEMPLATE = 'AT&TFORM\0\0\0\0DJVMDIRM\0\0\0\0'
DJVU_VERSION = 1

def main():
    description = __doc__.strip()
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-f', '--force', help=argparse.SUPPRESS)
    parser.add_argument('index', metavar='INDEX', help='index DjVu file (output)')
    parser.add_argument('page', metavar='PAGE', nargs='+', help='component DjVu files (input)')
    options = parser.parse_args()
    page_ids = []
    page_sizes = []
    index_filename = options.index
    index_dirname = os.path.dirname(index_filename)
    for file_name in options.page:
        dir_name, base_name = os.path.split(file_name)
        if dir_name != index_dirname:
            raise ValueError('All files needs to be in the same directory')
        page_size = os.path.getsize(file_name)
        if page_size >= 1 << 24:
            page_size = 0
        page_sizes += [page_size]
        page_ids += [base_name]
    with open(index_filename, 'wb') as index_file:
        index_file.write(DJVU_TEMPLATE)
        index_file.write(struct.pack('B', DJVU_VERSION))
        index_file.write(struct.pack('>H', len(page_ids)))
        index_file.flush()
        bzz = subprocess.Popen(['bzz', '-e', '-', '-'], stdin=subprocess.PIPE, stdout=index_file)
        try:
            for page_size in page_sizes:
                bzz.stdin.write(struct.pack('>I', page_size)[1:])
            for page_id in page_ids:
                bzz.stdin.write(struct.pack('>B', 1))
            for page_id in page_ids:
                bzz.stdin.write(page_id)
                bzz.stdin.write('\0')
        finally:
            bzz.stdin.close()
            bzz.wait()
        index_file_size = index_file.tell()
        i = 0
        while True:
            i = DJVU_TEMPLATE.find('\0' * 4, i)
            if i < 0:
                break
            index_file.seek(i)
            index_file.write(struct.pack('>I', index_file_size - i - 4))
            i += 4

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
