#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2007-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys
import subprocess

file_name = sys.argv[1]

p = subprocess.Popen(['/usr/bin/djvused', '-e', 'output-txt', file_name], stdout=subprocess.PIPE)
n = 1
try:
    for line in p.stdout:
        if line.startswith("select '"):
            line = 'select %d\n' % n
            n += 1
        sys.stdout.write(line)
finally:
    p.wait()

# vim:ts=4 sts=4 sw=4 et
