#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2007-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys
import subprocess

ap = argparse.ArgumentParser()
ap.add_argument('path', metavar='FILE')
options = ap.parse_args()

p = subprocess.Popen(['djvused', '-e', 'output-txt', options.path], stdout=subprocess.PIPE)
n = 1
try:
    for line in p.stdout:
        if line.startswith("select '"):
            line = 'select %d\n' % n
            n += 1
        sys.stdout.write(line)
finally:
    p.stdout.close()
    p.wait()

# vim:ts=4 sts=4 sw=4 et
